# Generated by Django 5.0.4 on 2024-05-08 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FlowData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('SensorID', models.TextField()),
                ('Date_n_Time', models.TextField()),
                ('Flow', models.TextField()),
            ],
            options={
                'db_table': 'Flow_Data',
            },
        ),
        migrations.CreateModel(
            name='HumidityData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('SensorID', models.TextField()),
                ('Date_n_Time', models.TextField()),
                ('Humidity', models.TextField()),
            ],
            options={
                'db_table': 'Humidity_Data',
            },
        ),
        migrations.CreateModel(
            name='PaintLevelData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('SensorID', models.TextField()),
                ('Date_n_Time', models.TextField()),
                ('PaintLevel', models.TextField()),
            ],
            options={
                'db_table': 'PaintLevel_Data',
            },
        ),
        migrations.CreateModel(
            name='PositionData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('SensorID', models.TextField()),
                ('Date_n_Time', models.TextField()),
                ('Position', models.TextField()),
            ],
            options={
                'db_table': 'Position_Data',
            },
        ),
        migrations.CreateModel(
            name='SurfaceQualityData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('SensorID', models.TextField()),
                ('Date_n_Time', models.TextField()),
                ('SurfaceQuality', models.TextField()),
            ],
            options={
                'db_table': 'SurfaceQuality_Data',
            },
        ),
        migrations.CreateModel(
            name='TemperatureData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('SensorID', models.TextField()),
                ('Date_n_Time', models.TextField()),
                ('Temperature', models.TextField()),
            ],
            options={
                'db_table': 'Temperature_Data',
            },
        ),
    ]
